# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finq_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update

# Mostrar el SQL en la consola 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
